name: bitcoin_dart
description: A Bitcoin library for Flutter written in Dart. BIP32, BIP39, P2PKH integration.
version: 2.0.3
homepage: https://github.com/saentari/bitcoin_dart/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bip39: ^1.0.6
  bip32: ^2.0.0
  pointycastle: ^3.6.0
  hex: ^0.2.0
  bs58check: ^1.0.2
  bech32: 0.2.1

dev_dependencies:
  test: ^1.15.4
